name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY_URI: ${{ secrets.ECR_REGISTRY_URI }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY_URI:$IMAGE_TAG .
          
          # Tag the Docker image
          docker tag $ECR_REGISTRY_URI:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REGISTRY_URI}:$IMAGE_TAG
          
          # Push the Docker image to ECR
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REGISTRY_URI}:$IMAGE_TAG
